HEADERS = {
    "accept": "application/json",
}

EMPTY_STRING = ""

ABILITIES = "abilities"
ABILITY = "ability"
BASE_STAT = "base_stat"
CHAIN = "chain"
COLOR = "color"
EN = "en"
EVOLUTION_CHAIN = "evolution_chain"
EVOLVES_TO = "evolves_to"
FLAVOR_TEXT = "flavor_text"
FLAVOR_TEXT_ENTRIES = "flavor_text_entries"
FRONT_DEFAULT = "front_default"
GENERA = "genera"
GENUS = "genus"
HABITAT = "habitat"
HEIGHT = "height"
IS_LEGENDARY = "is_legendary"
LANGUAGE = "language"
MAIN = "main"
MOVE = "move"
MOVES = "moves"
NAME = "name"
NULL = "null"
POWER = "power"
RESULTS = "results"
SPECIES = "species"
SPRITES = "sprites"
STATS = "stats"
TYPE = "type"
TYPES = "types"
URL = "url"
WEIGHT = "weight"